### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by gdalle** [adrhill/iclr2025-sparse-autodiff#16]
I think we should keep the demo section fairly short, and mostly focused on Jacobians because that's where our code is most efficient. The most interesting things to see are:

- colorings for simple matrix structures (diagonal, tridiagonal, banded, rectangular)
- colorings for neural network layers (convolution, pooling, activation)
- benchmarks on a simple case that is not the Brusselator. Maybe check out what the authors of the paper on implicit differentiation (Blondel et al) used as applications and pick one of those

**Comment by adrhill** [comment]
> colorings for simple matrix structures (diagonal, tridiagonal, banded, rectangular)

I'm not sure our audience needs to see all of these. Maybe this could even be misunderstood as being a requirement for coloring.

> colorings for neural network layers (convolution, pooling, activation)

Some remarks: Convolution would require using SCT's undocumented set types.
Jacobians of diagonal matrices are trivial, since they are diagonal.

> benchmarks on a simple case that is not the Brusselator. 

Maybe a toy example that can be scaled would help to convey the take-away that performance depends on the number of saved matrix-vector products vs. time for detection and coloring.

**Comment by gdalle** [comment]
> Maybe a toy example that can be scaled would help to convey the take-away that performance depends on the number of saved matrix-vector products vs. time for detection, coloring and decompression.

We could just take the finite differences operator `diff` and compose it with itself. If I'm not mistaken, `diff^n` has `n+1` bands in its Jacobian?

**Comment by adrhill** [comment]
How about `f(x) = diff(x .^ 2) + diff(reverse(x .^ 2))` from the DI docs?

**Comment by gdalle** [comment]
Sure but this has a fixed number of colors. By iterating diff first we can play with the number of colors

**Comment by adrhill** [comment]
Then let's do `diff^n` and iterate on it if the need arises. 👍
